version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
      POSTGRES_DB: medical_eval_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://medical_user:medical_password@db:5432/medical_eval_db
    depends_on:
      - db

volumes:
  db_data:

